### ISSUE TITLE
Error: Cannot find module 'C:projectsmy-fusion-app ode_modulessource-map-supportsource-map-support.js'

### ISSUE THREAD

**Issue by lgkonline** [fusionjs/create-fusion-app#35] opened 2018-08-08 07:15 UTC
Today I wanted to get started with Fusion.js and followed the guide on [https://fusionjs.com/docs/getting-started](https://fusionjs.com/docs/getting-started).
I've used `yarn create fusion-app my-fusion-app` to create a new project and ran the command `yarn run dev` to start developing. Then on the browser and in the console I've got this error message:
```
Error: Cannot find module 'C:projectsmy-fusion-app ode_modulessource-map-supportsource-map-support.js'

Function.Module._resolveFilename
module.js:547:15

Function.Module._load
module.js:474:25

Module.require
module.js:596:17

require
internal/module.js:11:18

Object.<anonymous>
C:\projects\my-fusion-app\.fusion\dist\development\server\server-main.js:2:1

Module._compile
module.js:652:30

Object.Module._extensions..js
module.js:663:10

Module.load
module.js:565:32

tryModuleLoad
module.js:505:12

Function.Module._load
module.js:497:3
```

Because of the missing backslashes on the missing module path, I suspect that this error only occurs because I'm using Windows. I also tested it on my MacBook and there everything works fine.

I'm not really sure if this is the correct repository this issue depends to. 😅

**Comment by KevinGrandon** [comment] 2018-08-08 17:07
Thank you for the bug report. Let's mark this as a duplicate of #461.

In the meantime, please try running the Fusion.js application from within Docker, using the steps found in: https://github.com/fusionjs/fusion-cli/issues/461#issuecomment-411294134

Here are the steps:
* Clone or download this folder: https://github.com/KevinGrandon/fusion-boilerplate/tree/master/docker-fusion-app
* Run: docker-compose up

**Closed by KevinGrandon** 2018-08-08 17:07 UTC

**Comment by maihungdev** [comment] 2018-12-21 13:15
> Thank you for the bug report. Let's mark this as a duplicate of [fusionjs/fusion-cli#461](https://github.com/fusionjs/fusion-cli/issues/461).
> 
> In the meantime, please try running the Fusion.js application from within Docker, using the steps found in: [fusionjs/fusion-cli#461 (comment)](https://github.com/fusionjs/fusion-cli/issues/461#issuecomment-411294134)
> 
> Here are the steps:
> 
> * Clone or download this folder: https://github.com/KevinGrandon/fusion-boilerplate/tree/master/docker-fusion-app
> * Run: docker-compose up

same issue
